DROP TABLE clientes CASCADE CONSTRAINTS;
DROP TABLE sucursales CASCADE CONSTRAINTS;
DROP TABLE empleados CASCADE CONSTRAINTS;
DROP TABLE productores CASCADE CONSTRAINTS;
DROP TABLE vinos CASCADE CONSTRAINTS;
DROP TABLE vende CASCADE CONSTRAINTS;
DROP TABLE suministra CASCADE CONSTRAINTS;
commit;
